/*
** Copyright (c) 2009-2011 by Silicon Laboratories
**
** $Id: si_voice_version.c,v 1.1 2012/08/21 09:43:53 krammer Exp $
**
** si_voice_version.c
** ProSLIC API Version
**
** Author(s): 
** cdp
**
** Distributed by: 
** Silicon Laboratories, Inc
**
** This file contains proprietary information.	 
** No dissemination allowed without prior written permission from
** Silicon Laboratories, Inc.
** 
** THIS FILE IS AUTOGENERATED - DO NOT MODIFY
**
*/

char *SiVoiceAPIVersion = "6.4.0";
